import 'package:mobx/mobx.dart';

part 'counter_store.g.dart'; // This file will be generated by MobX

class CounterStore = _CounterStore with _$CounterStore;

abstract class _CounterStore with Store {
  @observable
  int count = 0;

  @observable
  int count2 = 0;

  @action
  void increment() {
    count++;
  }

  @action
  void decrement() {
    count--;
  }

  @action
  void increment2() {
    count2++;
  }

  @action
  void decrement2() {
    count2--;
  }
}
