import 'package:mix_tube_application/repository/remote_repository/login_repository.dart';
import 'package:mobx/mobx.dart';

part 'login_store.g.dart'; // This file will be generated by MobX

class LoginStore = _LoginStore with _$LoginStore;

abstract class _LoginStore with Store {
  _LoginStore(this._repository);

  final LoginRepository _repository;

  @action
  Future login(String email, String password) async {
    _repository.register(email, password).then((e) {
      print(e);
    }).catchError((e) {
      print(e);
      if (e.code == 'user-not-found') {
        print('No user found for that email.');
      } else if (e.code == 'wrong-password') {
        print('Wrong password provided for that user.');
      }
    });
  }

  @action
  Future logout() async {
    await _repository.logout();
  }
}
